### ISSUE TITLE
Use minetest.register_on_item_eat

### ISSUE THREAD

**Issue by rubenwardy** [BlockMen/hud_hunger#15]
> minetest.register_on_item_eat(func(hp_change, replace_with_item, itemstack, user, pointed_thing))
> Called when an item is eaten, by minetest.item_eat
> Return true or itemstack to cancel the default item eat response (i.e.: hp increase)

**Comment by BlockMen** [comment]
Done in https://github.com/BlockMen/hunger
https://github.com/BlockMen/hunger/commit/30fea241d0d71e3bf8b70dd03ad12857d94841fc
