### ISSUE TITLE
hunger.lua unstable and still causing loads of server crashes

### ISSUE THREAD

**Issue by yo-we** [BlockMen/hud_hunger#17]
Hello,

I know that there are discussions ongoing on who should do the nil tests and stuff. I just have one comment to make on these discussions: As long as the official decision has not been taken, you _have_ to handle that on either side. Otherwise, the server continue crashing which means that the mod is totally useless (and even worse). Once the architecture is decided, you will apply it which will make atmost one side remove the tests.

Here the logs and description, we still try to find out what the machine is. At the end I put a copy of some discussion on the channel.

BUG description---->
This is yet another Hud related error appearing on the latest available version: commit 69a993861e. This error causes a server crash. We think that this is a very severe bug because crashing the server has a lot of bad and no good consequences. Furthermore, in terms of frequence, it appears very often. This totally compromises the game.

We can not proof the relation, but the error probability seems to be very high in the following scenario:

A player approaches a machine of another player, and the latter is not connected.

11:35:22: ERROR[main]: ERROR: An unhandled exception occurred: /home/minetest/.minetest/mods/hud/hunger.lua:379: attempt to perform arithmetic on local 'exhaus' (a nil value)
11:35:22: ERROR[main]: stack traceback:
11:35:22: ERROR[main]:  /home/minetest/.minetest/mods/hud/hunger.lua:379: in function 'callback'
11:35:22: ERROR[main]:  /opt/minetest-0.4.12/bin/../builtin/game/item.lua:467: in function </opt/minetest-0.4.12/bin/../builtin/game/item.lua:405>
11:35:22: ERROR[main]:  (tail call): ?
11:35:22: ERROR[main]:  /home/minetest/.minetest/mods/pipeworks/wielder.lua:334: in function 'act'
11:35:22: ERROR[main]:  /home/minetest/.minetest/mods/pipeworks/wielder.lua:109: in function 'wielder_on'
11:35:22: ERROR[main]:  /home/minetest/.minetest/mods/pipeworks/wielder.lua:145: in function 'action_on'
11:35:22: ERROR[main]:  ...netest/.minetest/mods/mesecons/mesecons/internal.lua:189: in function '?'
11:35:22: ERROR[main]:  ...est/.minetest/mods/mesecons/mesecons/actionqueue.lua:90: in function 'execute'
11:35:22: ERROR[main]:  ...est/.minetest/mods/mesecons/mesecons/actionqueue.lua:84: in function '?'
11:35:22: ERROR[main]:  ...opt/minetest-0.4.12/bin/../builtin/game/register.lua:341: in function <...opt/minetest-0.4.12/bin/../builtin/game/register.lua:329>
----< end of BUG description

part of the IRC discussion:

=== #minetest http://minetest.net
    Nihao   Greetings, oh protectors of the cubes
    Nihao   VanessaE: Sorry for yesterday, I missed something and have to say officially: The bug is _not_ coming from Quarry.
    VanessaE    no worries.
    VanessaE    it's the bones mod that's the issue, sorta.
    VanessaE    until the API is clarified it's still unsure whose fault it is
    Nihao   Understood.
    gamemanj    ...? Which API?
    Nihao   Now I need advice for the Hud....it has a commit, we take it and --big surprise-- the server crashes.
    VanessaE    gamemanj: the minetest modding API, regarding callbacks like can_dig
    Nihao   ...agina...and again...and .....
    VanessaE    Nihao: I don't know what you mean by "the Hud"
    Nihao   aigain
    VanessaE    there are a number of mods that affect the default HUD
    Nihao   Here is the trace: http://pastebin.com/ztmi0cCB
    VanessaE    oh, hunger mod.
    Nihao   YEp, sorry, I am not yet familiar with the expressions.
    VanessaE    that's a matter to take up with the authors of that mod.
    Nihao   Sure, give me names, I am in the mood
    VanessaE    and it's probably the samne thing
    VanessaE    a nil is being passed somewhere and that mod doesn't know how to handle it
    Nihao   What is so funny: It worked some weeks ago!
    gamemanj    ...It's not in the "hunger" mod, it's in "hud/hunger.lua"...in other words,
    gamemanj    the Hud mod's handling of hunger.
    Nihao   OK: I propose top-down.
    Nihao   The server crashes after a change on a stable mod.
    Nihao   After rewored rework still the same.
    Nihao   Then, it shouls revert to what was stable.
    Nihao   should*
    Nihao   And maybe apply more testing.
    VanessaE    oh you're right
    VanessaE    well anyway I've passed it on to the minetest core devs
    Nihao   OK. How can I coome to that situation?
    VanessaE    this needs an official ruling as far as the API is concerned.
    VanessaE    either the hud mod needs fixed or pipeworks does.
    Nihao   Please understand me well, I am not against anybody. Just not understanding how it should continue to work.
    Nihao   We have dozens of resets every day and can not get rid of them....
    gamemanj    Research into HUD complete, looks like dev is BlockMen, unless Nihao has a fork which didn't show up on google.
    Nihao   That would be perfect!
    gamemanj    why would that be perfect?
    gamemanj    is confused. Very confused.
    Nihao   Actually, it is BlockMen and the version we use is written in the link
    VanessaE    Nihao: it is important that you remember that a server crash is almost always due to mods you've installed. so if you get lots of crashes from a particular combo, you have no choice but to remove the offending mods and contact the developer(s)
    VanessaE    ..of those mods
    Nihao   OK.
    gamemanj    Aha! The line in question is: "exhaus = exhaus + new"
    Nihao   What is the best way you would suggest: opening an issue?
    gamemanj    "exhaus" is "local exhaus = hud.exhaustion[name]". I know what the bug is, sort of.
    VanessaE    occasionally a server will just...crash, for no obvious reason, which is then the minetest core devs domain. but mods are strictly the modders' areas to deal with, so you have to contact those modders on their github repo's, forum topics, IRC, etc.
    gamemanj    For some reason, it's not initializing/is forgetting the "exhaustion" value for a player...
    VanessaE    opening an issue is a good idea, on the respective mods' github pages. but looks like gamemanj here is already figuring out the issue with that particular mod
    gamemanj    The bug is caused when going near a machine,right?
    gamemanj    What if that machine were to be creating a FAKE PLAYER?
    Nihao   VanessaE: Thank you very much. I will open the issue.
    gamemanj    When the fake player digs a block, the callback is called.
    gamemanj    The callback then fails, because the fake player != a real player, so exhaustion isn't initialized.
    Nihao   it is not a fake player but a non-connected player
    Nihao   ....tha, I wrote.
    gamemanj    ...No, you don't understand. What machine was it?
    gamemanj    What machine?
    Nihao   I try to find out.
    gamemanj    ...I think it's a block breaker/block placer, or something doing that kind of thing.
    VanessaE    gamemanj: indeed, some pipeworks and technic machines have to create a "fake" player to do their actions with.
    Nihao   We do not have Quarry.
    VanessaE    some other mods have trouble with this because I guess not all fields/values in the player object are present? I'm not sure (I didn't write the machines in question)
    VanessaE    the modding API doesn't specify clearly what parts of a player object are mandatory
    gamemanj    The reason is because Hunger is assuming the player would connect "normally".
    gamemanj    It doesn't check if it ever initialized the exhaustion value.
    VanessaE    gamemanj: it would likely be triggered by a nodebreaker, that's part of the "wielder" object.
    VanessaE    (I don't _think_ the deployer is part of the wielder object)
    gamemanj    And even if the fake player doesn't have the same name as a real player,
    gamemanj    it would still trigger. But that's not the problem here.
    gamemanj    As it is, the minetest API is doing what it's supposed to, but hunger.lua isn't handling the possibility of uninitialized values.
    gamemanj    As it is, Nihao, I have a simple solution for a quick fix.
    gamemanj    Replace "local exhaus = hud.exhaustion[name]" with "local exhaus = hud.exhaustion[name] or 0".
    gamemanj    (again, a quick fix, and I'm not sure how well it will work)
    Nihao   gamemanj: Thanks a lot. I am not sure if the administrator is still willing to play but I will propose it.

**Comment by BlockMen** [comment]
Fixed in https://github.com/BlockMen/hunger
BlockMen/hunger@30fea24

Please open an issue there if this problem still occurs
