### ISSUE TITLE
Sleeping in bed removes the hotbar

### ISSUE THREAD

**Issue by poet-nohit** [BlockMen/hud_hunger#20]
How to reproduce:
- Create a new world with "minetest_game" as the base.
- Configure the world with "hud" as an added mod.
- Start the world 
- /giveme beds:bed
- /time 20000
- Place the bed and right-click it.

I'm not sure whether this is an issue with hud or beds because the normal hud just leaves the hotbar alone. Maybe something in the way hud_flags is implemented?

**Comment by poet-nohit** [comment]
I've manage to isolate the problem area: https://github.com/poet-nohit/minetest-spiffy/commit/0028b7d784755d80b00cb2d209014cf7025ea7f7

Not sure what type of bug you would call this, but there you go.

**Comment by BlockMen** [comment]
Ah, thanks for pointing out. It seems the flags are not set correct engineside by just using a few table values for set_hud_flags().
