### ISSUE TITLE
Crash 0.4.12-dev

### ISSUE THREAD

**Issue by amadin** [BlockMen/hud_hunger#24]
Public dedicated server 0.4.12-dev.

2015-07-30 10:34:46: ERROR[ServerThread]: 3d_armor: Player position is nil [set_player_armor]
2015-07-30 10:34:46: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2015-07-30 10:34:46: ERROR[main]: ...n/../games/minetest_game/mods/hud_hunger/hud/api.lua:89: attempt to index local 'elem2' (a nil value)
2015-07-30 10:34:46: ERROR[main]: stack traceback:
2015-07-30 10:34:46: ERROR[main]:   ...n/../games/minetest_game/mods/hud_hunger/hud/api.lua:89: in function 'swap_statbar'
2015-07-30 10:34:46: ERROR[main]:   .../games/minetest_game/mods/hud_hunger/hunger/init.lua:42: in function 'func'
2015-07-30 10:34:46: ERROR[main]:   /home/user/minetest/bin/../builtin/game/misc.lua:17: in function 'update_timers'
2015-07-30 10:34:46: ERROR[main]:   /home/user/minetest/bin/../builtin/game/misc.lua:49: in function '?'
2015-07-30 10:34:46: ERROR[main]:   /home/user/minetest/bin/../builtin/game/register.lua:341: in function </home/user/minetest/bin/../builtin/game/register.lua:329>

In thread 7f1670281740:
/home/user/minetest/minetest-master/src/server.cpp:509: void Server::step(float): A fatal error occurred: ...n/../games/minetest_game/mods/hud_hunger/hud/api.lua:89: attempt to index local 'elem2' (a nil value)
stack traceback:
    ...n/../games/minetest_game/mods/hud_hunger/hud/api.lua:89: in function 'swap_statbar'
    .../games/minetest_game/mods/hud_hunger/hunger/init.lua:42: in function 'func'
    /home/user/minetest/bin/../builtin/game/misc.lua:17: in function 'update_timers'
    /home/user/minetest/bin/../builtin/game/misc.lua:49: in function '?'
    /home/user/minetest/bin/../builtin/game/register.lua:341: in function </home/user/minetest/bin/../builtin/game/register.lua:329>
Debug stacks:
DEBUG STACK FOR THREAD 7f164f5fe700:
#0  virtual void\* EmergeThread::Thread()

(Leftover data: #1  MapBlock\* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string_, v3s16, MapSector_, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f164ffff700:
#0  virtual void\* EmergeThread::Thread()

(Leftover data: #1  MapBlock\* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string_, v3s16, MapSector_, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f16611f0700:
#0  virtual void\* EmergeThread::Thread()

(Leftover data: #1  MapBlock\* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string_, v3s16, MapSector_, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f1661bf1700:
#0  virtual void\* CurlFetchThread::Thread()

DEBUG STACK FOR THREAD 7f16625f2700:
#0  virtual void\* ServerThread::Thread()
#1  void Server::Receive()

(Leftover data: #2  virtual void Server::deletingPeer(con::Peer_, bool))
(Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment_, EmergeManager_, float, std::vector<PrioritySortedBlockTransfer>&))
(Leftover data: #4  void ItemStack::serialize(std::ostream&) const)
(Leftover data: #5  bool getCraftingResult(Inventory_, ItemStack&, std::vector<ItemStack>&, bool, IGameDef_))
(Leftover data: #6  void ItemStack::deSerialize(std::istream&, IItemDefManager_))
(Leftover data: #7  void ItemStack::deSerialize(std::istream&, IItemDefManager*))
DEBUG STACK FOR THREAD 7f1670281740:
#0  int main(int, char**)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server&, bool&)
#3  void Server::step(float)

(Leftover data: #4  void Server::DenyAccess_Legacy(irr::u16, const wstring&))
(Leftover data: #5  void Server::SendAccessDenied_Legacy(irr::u16, const wstring&))

**Comment by BlockMen** [comment]
Seems to be a problem when a player leaves (Player position is nil [set_player_armor] indicates that too.

Was that the only crash or did that happen often? If so, how often?

**Comment by amadin** [comment]
It was once, before this crash i update 3d_armor mod (modpack) with lava damage and water flow fix.

**Comment by BlockMen** [comment]
@amadin Ah, ic. Well, that could be the problem for your other issue you opend. Since hud checks the armor hud for changes it might have become incompatible.

Maybe you could request at @stujones11 repro to change his mod, so that it uses the hud api; instead of this mod using an ugly workaround.

**Comment by BlockMen** [comment]
Ok, seems for me that HUD should be compatible with the armor mod again. I will close #25 and this within a week if nothing new happens.
