### ISSUE TITLE
Lava don't deal damage, water and lava don't flow aftes some time.

### ISSUE THREAD

**Issue by amadin** [BlockMen/hud_hunger#25]
Lava don't deal damage, water and lava don't flow after some time if i add hunger mod before.
By process of elimination, removing one by one mods, I figured that the problem is in hunger mod, more precisely in HUD, if i delete HUD directory of hunger mod - lava begin deal damage and flowing, water begin flowing too.
0.4.12-dev updated 3-4 days ago, hunger mod last version too, mapgen7 with ehtereal mod. In log i can't see any errors. This bug on local dedicated server and on public server, players see this bug too.

**Comment by BlockMen** [comment]
I have no idea how the hud mod should cause this. This mod does not even check for any node nor does it have a globalstep, the hud elements are updated by events only (damage, air) by default and by hunger changes (when hunger enabled).
Do you have the itemwheel enabled? If not I guess that etheral and hunger somehow don't like. Check the dependencies of etheral and remove hud and hunger if present.

Thats all i can suggest right now

**Comment by amadin** [comment]
the hud mod is overriding the update_armor function without the new dtime parameter https://github.com/tenplus1/ethereal/issues/11

**Comment by BlockMen** [comment]
@amadin ok. See https://github.com/BlockMen/hud/issues/24#issuecomment-129847633
