### ISSUE TITLE
Crash when used with mesecons + pipeworks

### ISSUE THREAD

**Issue by est31** [BlockMen/hud_hunger#26]
Players can create a mesecon/pipeworks setup which leads to a crash every time they come close to it. The crash backtrace, some unneccessary parts removed:

```
2015-09-20 02:48:34: ERROR[Main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2015-09-20 02:48:34: ERROR[Main]: Runtime error from mod 'hud' in callback environment_Step(): hud/hunger.lua:34
8: attempt to perform arithmetic on local 'exhaus' (a nil value)
2015-09-20 02:48:34: ERROR[Main]: stack traceback:
hud/hunger.lua:348: in function 'callback'
builtin/game/item.lua:494: in function 'on_dig'
pipeworks/wielder.lua:325: in function 'act'
pipeworks/wielder.lua:109: in function 'wielder_on'
pipeworks/wielder.lua:145: in function 'action_on'
mesecons/mesecons/internal.lua:189: in function <mesecons/mesecons/internal.lua:184>
mesecons/actionqueue.lua:90: in function 'execute'
mesecons/mesecons/actionqueue.lua:84: in function <mesecons/mesecons/actionqueue.lua:61>
```

My theory to this is:
1. players can create setups with pipeworks to automatically influence the world
2. these setups do those actions under a player's name **even if that player is offline**. To accomplish this, they [create fake players](https://github.com/VanessaE/pipeworks/blob/5822f60ba9cbebe45c1f82fa06dc93b747ba71a6/wielder.lua#L75-L107).
3. Now the hud mod relies on `minetest.register_on_joinplayer` to be called for a player since server start so that their entry in the `hud.exhaustion` table is initialized to a number.

**Comment by est31** [comment]
The fix is I think to just check `exhaus` for nil in the function the crash occured, and if it is, abort.

``` diff
diff --git a/hunger.lua b/hunger.lua
index 8c4e787..48be2bb 100644
--- a/hunger.lua
+++ b/hunger.lua
@@ -336,6 +336,9 @@ function hud.handle_node_actions(pos, oldnode, player, ext)
        end
        local name = player:get_player_name()
        local exhaus = hud.exhaustion[name]
+       if not exhaus then
+               return
+       end
        local new = HUD_HUNGER_EXHAUST_PLACE
        -- placenode event
        if not ext then
```

**Comment by ssieb** [comment]
Are you sure you have the right mod?  I don't see a hunger.lua file anywhere in this repo or the hunger repo.

**Comment by ssieb** [comment]
Ok, I see. You have an old version.  On April 2, the hunger parts were split into the separate hunger mod.

**Comment by est31** [comment]
Ah thanks, haven't checked that.
