### ISSUE TITLE
life HUD appearing double on windows

### ISSUE THREAD

**Issue by gangelop** [BlockMen/hud_hunger#9]
![gpov0yt](https://cloud.githubusercontent.com/assets/1893345/4173653/e5854d18-355f-11e4-8b7d-6543de0a3ec0.png)

On minetest client `0.4.10` on Windows.

Unfortunately, I might have intermittent access to this computer at best, so it's hard to debug. Maybe someone else has ran into this issue?

**Comment by rubenwardy** [comment]
Edit: Oops, thought this was minetest/minetest Ignore this.

**Comment by BlockMen** [comment]
Hmm...that should have been fixed in the engine a long time already. Have you modified some files in the builtin folder?
Ans does this happen aswell with just this mod enabled?

**Comment by BlockMen** [comment]
Please open new issue if present in Version 2.0 or later

**Comment by Fixer-007** [comment]
Happened to me few times.
